### ISSUE TITLE
modules in package are to be avoided

### ISSUE THREAD

**Issue by zierenberg** [zierenberg/MonteCarloX.jl#27]
Restructure full package to avoid modules. This might cause some problems with the current API. 
For example
```
Metropolis.accept()
```
would have to be changed to 
```
metropolis()
```
or we introduce on Georges advice singletons and let multiple dispatch solve the problem, e.g.
```
struct Metropolis end
alg = Metroppolis()
function accept(a,b,alg::Metropolis)
function accept(a,b,alg::X) 
```

**Comment by fmikulasch** [comment]
this can be closed after commit `0d916817c50dc226935ca9896b2a163224abd827`
