### ISSUE TITLE
Wrapper to generate "Apps" ?

### ISSUE THREAD

**Issue by zierenberg** [zierenberg/MonteCarloX.jl#34]
Should we be interested in providing a wrapper to generate julia "Apps" with precompiled code that can be send to other computers, e.g. clusters? Or is this inefficient? Or can we somehow provide another way to get precompiled code that can be executed for a broad range or parameters?

see here for further information on Apps:
https://github.com/JuliaLang/PackageCompiler.jl

**Comment by fmikulasch** [comment]
I think it's a lot easier to just run Julia. If it's not necessary performance wise (startup time) then I don't see a good reason.

**Comment by zierenberg** [comment]
How do you deal with cluster submit scripts then. You cannot start them from REPL. You will have to write a julia script and pass some arguments? I have not done this yet, but the general workflow one would like to have is
1) develop program (should be nice now with MCX in REPL)
2) compile (freeze?) 
3) run for tons of different parameters by command line call (within cluster submit script) such as
```
> ./my_awesome_program -N 1000 -t 10 -s 1000
```

**Comment by fmikulasch** [comment]
You can get passed arguments from the array `ARGS`. Compiling doesn't add any additional possibilities (and real advantages I feel). If the compilation time is the bottleneck then any user could apply the package compiler himself if they want to.

**Comment by zierenberg** [comment]
Oka, convinced.
